version: "3.9"


services:

  attacker:
    build: ./attacker
    container_name: attacker
    privileged: true
    networks:
      mitm_net:
        ipv4_address: 192.168.15.3

  client:
    build: ./client
    container_name: client
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      mitm_net:
        ipv4_address: 192.168.15.4
    depends_on:
      - attacker

networks:
  mitm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24
  bridge_net:
    driver: bridge
